---
- hosts: myservers
  become: yes
  tasks:
  - name: Install pre-req packages
    package:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
      update_cache: yes

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Install Docker
    apt: 
      name: 
      - docker.io
      state: latest
      update_cache: yes

  - name: Ensure group "docker" exists with correct gid
    ansible.builtin.group:
      name: docker
      state: present
      gid: 1750

  - name: create a docker user
    ansible.builtin.user:
      name: docker
      groups: docker
      append: yes

  - name: adding existing user to docker group
    ansible.builtin.user:
      name: ubuntu
      groups: docker
      append: yes

  - name: Change ownership to root:docker on docker.sock
    ansible.builtin.file:
      path: /var/run/docker.sock
      owner: root
      group: docker
      mode: '0660'